apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
  namespace: k8sgpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
      - name: nginx
        image: nginx:invalid-tag
